### PR TITLE
WIP: Update example dapp to use wallet connect version 2

### PR DESCRIPTION
**Pull request by EdgarBarrantes**
Made just enough changes for the app to work with v2, it's missing code for the three example actions. 
I wasn't able to test properly with [v2 test wallet](https://github.com/WalletConnect-Labs/walletconnect-v2-test-wallet), will check later on where the issue is. 

This PR does:
- It ppdates repo with original org code.
- Updated version of WC client library and made it create the QR code.

Caveats:
- It leaves some code that might not be useful anymore and some commented out imports, not use if those are going to be necessary afterwards. 

Couple of things I noticed: 
- Not sure if this is ok for v2, but I found the resulting uri does not follow EIP-1328, `relay` instead of `bridge`. Is that the new standard?
- After copying uri, session is not created on the wallet (no Approve/Reject buttons). I'll check the wallet later. 

Overall, I'm doing this to play and learn about Wallet Connect. Let me know if I can help further, really like this project, I use it pretty much every day.

### CODE REVIEW

**Comment by pedrouid** [comment]
Hey @EdgarBarrantes, thanks for jumping in. I didn't actually notice it at first and then I ended up overwriting master

I've merged master which may have affected some of your changes but I will give it a go and see if it still runs smoothly

**Comment by pedrouid** [comment]
Managed to tweak a few changes from the latest alpha and got it running. The bad news is that I've now hit the same issues connecting like you 😅 

Screen Shot 2021-01-11 at 19 25 01

**Comment by EdgarBarrantes** [comment]
@pedrouid glad it went smooth! Yeah I bumped into that and wasn't sure if it was something I was doing wrong or the fact that the example wallet was still on development and left it at that. 
I'll try to check out how did this go later today and see if I can tinker a bit more. Feel free to let me know if there is a specific part of the project I can lend a hand to.

**Comment by pedrouid** [comment]
Actually this latest issue was related to a recent change that I made to how pairing metadata is handled but now I have fixed it for alpha.17

Screen Shot 2021-01-11 at 20 30 34

Now need to listen to session proposal and render the popup to approve sessions

If you are interested to contribute... feel free to reach out to me on Telegram: @pedrouid

**Pull request merged**
